### ISSUE TITLE
Error ibazel

### ISSUE THREAD

**Issue by afifalfiano** [afifalfiano/angular-bazel#2]
asus  ~/Documents/Bazel_Research/angular9   staging ●✚  ibazel run src:devserver 
iBazel [9:07AM]: Error getting Bazel info exit status 2
iBazel [9:07AM]: Querying for files to watch...
iBazel [9:07AM]: Error getting Bazel info exit status 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7a2a00]

goroutine 1 [running]:
main.(*IBazel).realLocalRepositoryPaths(0xc0000ee000, 0x921e00, 0xc0000a86c0, 0x0)
        ibazel/ibazel_unix.go:31 +0x50
main.(*IBazel).queryForSourceFiles(0xc0000ee000, 0xc000102030, 0x24, 0x43d01f, 0xc000036800, 0x4d7c1c, 0xc00013c014, 0x7ffd2a9df0b9)
        ibazel/ibazel.go:454 +0x6e
main.(*IBazel).watchFiles(0xc0000ee000, 0xc000102030, 0x24, 0x91f800, 0xc0000a6020)
        ibazel/ibazel.go:502 +0x5d
main.(*IBazel).iteration(0xc0000ee000, 0x879818, 0x3, 0xc000135e10, 0xc000082e80, 0x1, 0x1, 0x7ffd2a9df0b9, 0xd)
        ibazel/ibazel.go:310 +0x947
main.(*IBazel).loop(0xc0000ee000, 0x879818, 0x3, 0xc000135e10, 0xc000082e80, 0x1, 0x1, 0x0, 0x0)
        ibazel/ibazel.go:270 +0xfb
main.(*IBazel).Run(0xc0000ee000, 0x7ffd2a9df0b9, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0)
        ibazel/ibazel.go:252 +0xe3
main.handle(0xc0000ee000, 0x7ffd2a9df0b5, 0x3, 0xc000084170, 0x1, 0x1)
        ibazel/main.go:193 +0x12d
main.main()
        ibazel/main.go:178 +0x2f9

**Comment by afifalfiano** [comment]
```
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Starting local Bazel server and connecting to it...
bazel-bin: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project/bazel-out/k8-fastbuild/bin
bazel-genfiles: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project/bazel-out/k8-fastbuild/bin
bazel-testlogs: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project/bazel-out/k8-fastbuild/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/command.log
committed-heap-size: 93MB
execution_root: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project
gc-count: 8
gc-time: 107ms
install_base: /home/asus/.cache/bazel/_bazel_asus/install/5f3a0e9dbcdf67475c08459b42b1f93c
java-home: /home/asus/.cache/bazel/_bazel_asus/install/5f3a0e9dbcdf67475c08459b42b1f93c/embedded_tools/jdk
java-runtime: OpenJDK Runtime Environment (build 11.0.2+7-LTS) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 11.0.2+7-LTS, mixed mode) by Azul Systems, Inc.
max-heap-size: 1220MB
output_base: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef
output_path: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project/bazel-out
package_path: %workspace%
release: release 2.1.0
repository_cache: /home/asus/.cache/bazel/_bazel_asus/cache/repos/v1
server_log: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/java.log.asus-virtualbox.asus.log.java.20200605-152342.3117
server_pid: 3117
used-heap-size: 42MB
workspace: /home/asus/Documents/Bazel_Research/angular9
```
